src/main/java/no/nav/foreldrepenger/oversikt/domene/AktørId.java, src/main/java/no/nav/foreldrepenger/oversikt/domene/FamilieHendelse.java, src/main/java/no/nav/foreldrepenger/oversikt/domene/SakES0.java, src/main/java/no/nav/foreldrepenger/oversikt/domene/SakFP0.java, src/main/java/no/nav/foreldrepenger/oversikt/domene/SakSVP0.java, src/main/java/no/nav/foreldrepenger/oversikt/innhenting/BehandlingHendelseHåndterer.java, src/main/java/no/nav/foreldrepenger/oversikt/innhenting/EsSak.java, src/main/java/no/nav/foreldrepenger/oversikt/innhenting/FpSak.java, src/main/java/no/nav/foreldrepenger/oversikt/innhenting/HentSakTask.java, src/main/java/no/nav/foreldrepenger/oversikt/innhenting/Sak.java, src/main/java/no/nav/foreldrepenger/oversikt/innhenting/SvpSak.java, src/main/java/no/nav/foreldrepenger/oversikt/server/JettyServer.java, src/test/java/no/nav/foreldrepenger/oversikt/DBSakRepositoryTest.java, src/test/java/no/nav/foreldrepenger/oversikt/domene/SakFP0TilDtoMapperTest.java, src/test/java/no/nav/foreldrepenger/oversikt/saker/SakerDtoMapperTest.java, src/test/java/no/nav/foreldrepenger/oversikt/saker/SakerRestTest.java
https://github.com/navikt/fp-sak/pull/5757
=> Familiehendelse på sak

src/main/java/no/nav/foreldrepenger/oversikt/innhenting/BehandlingHendelseHåndterer.java, src/main/java/no/nav/foreldrepenger/oversikt/innhenting/FpSakRestKlient.java, src/main/java/no/nav/foreldrepenger/oversikt/innhenting/FpsakTjeneste.java, src/main/java/no/nav/foreldrepenger/oversikt/innhenting/HentSakTask.java, src/test/java/no/nav/foreldrepenger/oversikt/saker/SakerRestTest.java, src/test/java/no/nav/foreldrepenger/oversikt/stub/FpsakTjenesteStub.java
https://github.com/navikt/fp-sak/pull/5761
=> Spør fpsak på saksnummer, ikke behandling id

pom.xml, src/main/java/no/nav/foreldrepenger/oversikt/domene/NullUtil.java, src/main/java/no/nav/foreldrepenger/oversikt/domene/fp/Uttaksperiode.java, src/main/java/no/nav/foreldrepenger/oversikt/domene/svp/Aktivitet.java, src/main/java/no/nav/foreldrepenger/oversikt/domene/svp/ArbeidsforholdUttak.java, src/main/java/no/nav/foreldrepenger/oversikt/domene/svp/AvslutningUtleder.java, src/main/java/no/nav/foreldrepenger/oversikt/domene/svp/DtoMapper.java, src/main/java/no/nav/foreldrepenger/oversikt/domene/svp/OppholdPeriode.java, src/main/java/no/nav/foreldrepenger/oversikt/domene/svp/ResultatÅrsak.java, src/main/java/no/nav/foreldrepenger/oversikt/domene/svp/SakSVP0.java, src/main/java/no/nav/foreldrepenger/oversikt/domene/svp/SvpPeriode.java, src/main/java/no/nav/foreldrepenger/oversikt/domene/svp/SvpSøknad.java, src/main/java/no/nav/foreldrepenger/oversikt/domene/svp/SvpVedtak.java, src/main/java/no/nav/foreldrepenger/oversikt/domene/svp/Tilrettelegging.java, src/main/java/no/nav/foreldrepenger/oversikt/domene/svp/TilretteleggingPeriode.java, src/main/java/no/nav/foreldrepenger/oversikt/domene/svp/TilretteleggingType.java, src/main/java/no/nav/foreldrepenger/oversikt/innhenting/HentSakTask.java, src/main/java/no/nav/foreldrepenger/oversikt/innhenting/SvpSak.java, src/main/java/no/nav/foreldrepenger/oversikt/saker/SakerDtoMapper.java, src/test/java/no/nav/foreldrepenger/oversikt/domene/fp/SakFP0Test.java, src/test/java/no/nav/foreldrepenger/oversikt/domene/svp/AvslutningUtlederTest.java, src/test/java/no/nav/foreldrepenger/oversikt/domene/svp/DtoMapperTest.java, src/test/java/no/nav/foreldrepenger/oversikt/saker/SakerDtoMapperTest.java, src/test/java/no/nav/foreldrepenger/oversikt/saker/SakerRestTest.java, src/test/java/no/nav/foreldrepenger/oversikt/saker/SakerTest.java
Fjerner tilretteleggingsperioder der det er overlappende opphold ut mot innsyn/søknad. Lagrer overlapp i db
Sak i db :
```json
{
"type": "SVP0",
"vedtak": [
{
"arbeidsforhold": [
{
"behovFom": "2023-06-08",
"aktivitet": {
"type": "SELVSTENDIG_NÆRINGSDRIVENDE"
},
"svpPerioder": [
{
"fom": "2023-06-08",
"tom": "2023-08-24",
"resultatÅrsak": "INNVILGET",
"utbetalingsgrad": 100.0,
"tilretteleggingType": "INGEN"
}
]
},
{
"behovFom": "2023-04-15",
"aktivitet": {
"type": "ORDINÆRT_ARBEID",
"arbeidsgiver": "993110469",
"arbeidsforholdId": "ce3aaf6c-d7c7-44f2-bac4-715f6b9cad6e"
},
"svpPerioder": [
{
"fom": "2023-04-15",
"tom": "2023-08-24",
"resultatÅrsak": "INNVILGET",
"utbetalingsgrad": 100.0,
"tilretteleggingType": "INGEN"
}
]
}
],
"vedtakstidspunkt": "2023-06-15T15:43:50.075"
},
{ …
```
=> Utvider saksmodell for svp

src/main/resources/META-INF/beans.xml
Ikke kritisk - men greit å få det rettet.
=> Fix mangel i beans xml schema path

src/main/java/no/nav/foreldrepenger/oversikt/drift/CleanNextBucketBatchTask.java, src/main/java/no/nav/foreldrepenger/oversikt/drift/RekjørFeiledeTasksBatchTask.java
Finner ikke helt ut hvordan disse skal startes?
Bruke /create i ProsessTaskRestTjeneste maybe?
=> task for å cleane ferdig tasks + task for å retry feilet tasks

pom.xml
Ingen endring av tokenflow nødvendig
=> Felles 5.1.0 og oppdatert auditlog.vendor

src/main/java/no/nav/foreldrepenger/oversikt/arkiv/DokumentArkivTjeneste.java, src/main/java/no/nav/foreldrepenger/oversikt/arkiv/EnkelJournalpost.java, src/main/java/no/nav/foreldrepenger/oversikt/innhenting/BehandlingHendelseHåndterer.java, src/main/java/no/nav/foreldrepenger/oversikt/innhenting/journalføringshendelse/DokumentType.java, src/main/java/no/nav/foreldrepenger/oversikt/innhenting/journalføringshendelse/HentDataFraJoarkForHåndteringTask.java
Litt hårete, men tror det dekker?
=> Henter tilbakekreving ved utgående journalpost fra fptilbake

src/main/java/no/nav/foreldrepenger/oversikt/innhenting/BehandlingHendelseHåndterer.java, src/main/java/no/nav/foreldrepenger/oversikt/innhenting/BehandlingMigreringHåndterer.java, src/main/java/no/nav/foreldrepenger/oversikt/innhenting/journalføringshendelse/HentDataFraJoarkForHåndteringTask.java, src/main/java/no/nav/foreldrepenger/oversikt/innhenting/journalføringshendelse/HentInntektsmeldingerTask.java, src/main/java/no/nav/foreldrepenger/oversikt/innhenting/journalføringshendelse/HentManglendeVedleggTask.java, src/main/java/no/nav/foreldrepenger/oversikt/innhenting/journalføringshendelse/HentTilbakekrevingTask.java
=> Raskere oppdatering av tilbakekreving hvis uttalelse fra bruker

pom.xml, src/main/java/no/nav/foreldrepenger/oversikt/server/JacksonJsonConfig.java, src/main/java/no/nav/foreldrepenger/oversikt/server/JettyServer.java
JacksonFormatMapper har flyttet seg litt. Bør vi test noe mer før dev ?
=> EE10 oppsett

pom.xml, src/main/java/no/nav/foreldrepenger/oversikt/drift/CleanNextBucketBatchTask.java, src/main/java/no/nav/foreldrepenger/oversikt/drift/RekjørFeiledeTasksBatchTask.java, src/main/java/no/nav/foreldrepenger/oversikt/innhenting/HentSakTask.java, src/main/java/no/nav/foreldrepenger/oversikt/innhenting/journalføringshendelse/HentDataFraJoarkForHåndteringTask.java, src/main/java/no/nav/foreldrepenger/oversikt/oppgave/MinSideAvsluttOppgaveTask.java, src/main/java/no/nav/foreldrepenger/oversikt/oppgave/MinSideBeskjedVedMottattSøknadTask.java, src/main/java/no/nav/foreldrepenger/oversikt/oppgave/MinSideOpprettOppgaveTask.java
Dere får se etter om det er flere som går asynkront til brukeroppslag og som kan få pri 2 - eller om jeg har satt pri 2 feil sted
=> Siste bom 331

pom.xml
Litt penere feilmelding ved 503 ved kall mot tokendings bl.a
=> Bump felles og fp-kontrakter

pom.xml
downgrade til forrige major versjon, da siste inneholder breaking changes for oss
=> Nedgrader tms varsler

pom.xml, src/main/resources/application-dev-gcp.properties, src/main/resources/application-prod-gcp.properties, src/test/java/no/nav/foreldrepenger/oversikt/oppgave/MinSideTjenesteTest.java
1. Legger til en liten sanitysjekk av tjenesten, herunder også at mapperen fungerer. 
2. Minside-varsel har releaset ny versjon med fikset builder, jeg bumper til den.
3. Innsyn er på ny url, legger inn nye innsynslenker i config
=> Bump minside/tms varsler

pom.xml, src/main/java/no/nav/foreldrepenger/oversikt/domene/fp/Gradering.java, src/main/java/no/nav/foreldrepenger/oversikt/domene/fp/Uttaksperiode.java, src/main/java/no/nav/foreldrepenger/oversikt/domene/svp/Aktivitet.java, src/main/java/no/nav/foreldrepenger/oversikt/innhenting/HentSakTask.java, src/main/java/no/nav/foreldrepenger/oversikt/innhenting/SvpSak.java, src/test/java/no/nav/foreldrepenger/oversikt/domene/svp/DtoMapperTest.java, src/test/java/no/nav/foreldrepenger/oversikt/saker/SakerDtoMapperTest.java, src/test/java/no/nav/foreldrepenger/oversikt/saker/SakerRestTest.java, src/test/java/no/nav/foreldrepenger/oversikt/saker/SakerTest.java
Må opgradere fpsoknad-felles.version når [denne](https://github.com/navikt/fpsoknad-felles/pull/409) er merget
=> Legg til arbeidsgivernavn paa aktivitet

pom.xml, src/main/java/no/nav/foreldrepenger/oversikt/domene/fp/BrukerRolle.java, src/main/java/no/nav/foreldrepenger/oversikt/domene/fp/FpSøknad.java, src/main/java/no/nav/foreldrepenger/oversikt/innhenting/BehandlingHendelseHåndterer.java, src/main/java/no/nav/foreldrepenger/oversikt/innhenting/FpSak.java, src/main/java/no/nav/foreldrepenger/oversikt/innhenting/HentSakTask.java, src/main/java/no/nav/foreldrepenger/oversikt/oppgave/MinSideBeskjedMorsArbeidTask.java, src/main/java/no/nav/foreldrepenger/oversikt/oppgave/MinSideTjeneste.java, src/test/java/no/nav/foreldrepenger/oversikt/DBSakRepositoryTest.java, src/test/java/no/nav/foreldrepenger/oversikt/domene/fp/SakFP0Test.java, src/test/java/no/nav/foreldrepenger/oversikt/oppgave/MinSideBeskjedMorsArbeidTaskTest.java, src/test/java/no/nav/foreldrepenger/oversikt/saker/AnnenPartSakTjenesteTest.java, src/test/java/no/nav/foreldrepenger/oversikt/saker/SakerDtoMapperTest.java, src/test/java/no/nav/foreldrepenger/oversikt/saker/SakerRestTest.java, src/test/java/no/nav/foreldrepenger/oversikt/saker/SakerTest.java
… i arbeid
https://github.com/navikt/fp-sak/pull/7203
https://github.com/navikt/fp-kontrakter/pull/614
Disabled i prod. Har igjen å få bekreftet selve innholdet i varselet (og ekstern varsling).
=> TFP-6060 beskjed til mor hvis far/medmor sender søknad med mors arbeid uten dokumentasjon. Disabled i prod

src/main/resources/application-dev-gcp.properties
=> TFP-6059 endepunkt aareg ereg dev

src/main/java/no/nav/foreldrepenger/oversikt/aareg/ArbeidsforholdTjeneste.java, src/main/java/no/nav/foreldrepenger/oversikt/aareg/MineArbeidsforholdTjeneste.java
Samme feilretting som vi gjorde i fp-abakus
=> TFP-6059 filter permisjon innhentingsintervall

src/main/java/no/nav/foreldrepenger/oversikt/saker/PdlKlient.java, src/main/java/no/nav/foreldrepenger/oversikt/saker/PdlKlientSystem.java
Ganske åpenbart tiltak - før vi gjør noe mer i retning av å innføre mer sentral tilgangsstyring.
Det trengs litt mer oversikt + konseptarbeid å gå opp god støtte - fx koblet sak vs ident+fhDato.
=> tilgang: Bedre caching av ident, alder, mv

pom.xml
Reverts navikt/fp-oversikt#371
=> Revert "Bump the interne-deps group with 7 updates"

src/main/java/no/nav/foreldrepenger/oversikt/oppslag/OppslagTjeneste.java, src/test/java/no/nav/foreldrepenger/oversikt/oppslag/OppslagTjenesteTest.java, src/test/java/no/nav/foreldrepenger/oversikt/stub/DummyInnloggetTestbruker.java
tror disse kjøres i parallell og går i bena på hverandre
=> flaky testfix

src/main/java/no/nav/foreldrepenger/oversikt/arbeid/AktivitetskravArbeidDokumentasjonsKravArbeidsforholdTjeneste.java, src/main/java/no/nav/foreldrepenger/oversikt/arbeid/AktivitetskravMåDokumentereMorsArbeidTjeneste.java, src/main/java/no/nav/foreldrepenger/oversikt/arbeid/ArbeidRest.java, src/main/java/no/nav/foreldrepenger/oversikt/arbeid/PeriodeMedAktivitetskravType.java, src/main/java/no/nav/foreldrepenger/oversikt/arbeid/PerioderMedAktivitetskravArbeid.java, src/test/java/no/nav/foreldrepenger/oversikt/aareg/MorsAktivitetTest.java, src/test/java/no/nav/foreldrepenger/oversikt/arbeid/AktivitetskravMåDokumentereMorsArbeidTjenesteTest.java
For tilfelle av 14-14 så gjelder aktivitetskrav både for uttak (utover minsterett) og utsettelse.
For uttak er kravet til mors stilling 75% eller mer, for utsettelse er kravet en stillingsprosent mer enn 0%.
Forslag: Utvide request med en periodetype null / UTTAK / UTSETTELSE - der null impliserer uttak.
=> TFP-6265 bare far rett, mor arbeid 1% eller mer
